### ISSUE TITLE
Gender Symbols rendering in Emoji List

### ISSUE THREAD

**Issue by aphirst** [thermatk/TgEmojiReplacer#5]
![photo_2016-10-21_06-34-29](https://cloud.githubusercontent.com/assets/1735556/19586756/b4375a46-9758-11e6-899d-e6a728abacea.jpg)

Sorry about the colour tint, I forgot I still had Twilight running.

I have this issue in 1.1 (I downloaded the APK directly from github a few minutes ago and rebooted), but this specific issue was also present in 1.0.

CM 13 (Android 6.0.1), ASUS Zenfone 2, Telegram 3.13.1. If you need any more info, feel free to ask.

**Comment by thermatk** [comment]
:)
I think there is only one way to fix this mess properly, which is to replace assets instead of hooking methods. 
https://github.com/DrKLO/Telegram/tree/master/TMessagesProj/src/main/assets/emoji
Asset replacement is pretty easy to do, but one needs to write a new program to generate these asset files from different emoji fonts. As a side effect, it will be easy to switch fully and properly between many emoji sets afterwards 👍

**Comment by thermatk** [comment]
Images with Twemoji are ready, so the path is certainly possible 👍 
Wrote about it in Telegram-FOSS https://github.com/slp/Telegram-FOSS/issues/53, but the work is done in EMOJITOOLS dir here.

**Comment by thermatk** [comment]
Algorithm:
1. Get latest EmojiData.java(TMessagesProj/src/main/java/org/telegram/messenger/EmojiData.java)
2. Add fixEmoji method from TMessagesProj/src/main/java/org/telegram/messenger/Emoji.java
3. Add my method that outputs to an external file, since I couldn't find a reliable way to get codepoints for emoji 4.0 in Java, and also because they are actually not really standard... very hacky things happening here
4. To use the twitter's js lib next step is the small html file emojiConverter.html where you past the output of step 2, convert it to codepoints and copypaste it to another file.
5. There are some 5 special cases of still wrongly formatted emojis here, for whatever reason, fix them manually by searching for closest names in the current twemoji set(in all cases just delete the unnecessary fe0f, but it's placed randomly)
6. Run the Main.java file, which has all possible workarounds there. It uses the EmojiData.java, converted codepoints from step 5 and twemoji folder with pngs and generates the final assets.

**Comment by thermatk** [comment]
Google Noto is done as well. Steps:
1. Using pngs from https://github.com/googlei18n/noto-emoji
2. For some missing there, using https://github.com/MitchTalmadge/Emoji-Tools to extract pngs from latest Noto Color Emoji font https://www.google.com/get/noto/ . Still, latest set of Google's emoji isn't fully equiped with rare flags, nothing I can do here.

**Comment by thermatk** [comment]
Ok, moved it to a separate repo now
https://github.com/thermatk/TelegramEmojiGenerator

**Comment by thermatk** [comment]
Use the newest version of TelegramReEmoji(renamed) from Xposed repo. Now there is a choice in the module's settings too! Enjoy
